import { buildFamilyGroups, buildPersonRecord } from "./family";
import { buildLandDetails, buildValuation } from "./calculations";
export const sampleHouseholdBundle = (() => {
    const household = {
        id: "11111111-1111-1111-1111-111111111111",
        villageId: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        houseId: "MAR-0001",
        headPersonName: "Ramesh Patil",
        landOwnerName: "Ramesh Patil",
        addressText: "Marda village main road",
        locality: "Ward 1",
        status: "DRAFT",
        isLocked: false,
    };
    const persons = [
        buildPersonRecord({
            id: "21111111-1111-1111-1111-111111111111",
            householdId: household.id,
            fullName: "Ramesh Patil",
            relationToLandOwner: "PRIMARY_LAND_OWNER",
            maritalStatus: "MARRIED",
            religion: "HINDU",
            casteCategory: "OBC",
        }),
        buildPersonRecord({
            id: "22222222-2222-2222-2222-222222222222",
            householdId: household.id,
            fullName: "Sita Patil",
            relationToLandOwner: "PRIMARY_LAND_OWNER_SPOUSE",
            maritalStatus: "MARRIED",
            religion: "HINDU",
            casteCategory: "OBC",
            dependentOnLandOwner: true,
        }),
        buildPersonRecord({
            id: "23333333-3333-3333-3333-333333333333",
            householdId: household.id,
            fullName: "Mahesh Patil",
            relationToLandOwner: "SON",
            maritalStatus: "MARRIED",
            marriageDate: "2018-06-12",
            religion: "HINDU",
            casteCategory: "OBC",
            familyGroupCode: "F2",
            includeInSurvey: true,
        }),
        buildPersonRecord({
            id: "24444444-4444-4444-4444-444444444444",
            householdId: household.id,
            fullName: "Anita Patil",
            relationToLandOwner: "DAUGHTER_IN_LAW",
            maritalStatus: "MARRIED",
            religion: "HINDU",
            casteCategory: "OBC",
            manualFamilyStatus: "SEPARATE",
            familyGroupCode: "F2",
        }),
        buildPersonRecord({
            id: "25555555-5555-5555-5555-555555555555",
            householdId: household.id,
            fullName: "Suresh Patil",
            relationToLandOwner: "SON",
            maritalStatus: "UNMARRIED",
            religion: "HINDU",
            casteCategory: "OBC",
            dependentOnLandOwner: true,
        }),
        buildPersonRecord({
            id: "26666666-6666-6666-6666-666666666666",
            householdId: household.id,
            fullName: "Meena Patil",
            relationToLandOwner: "DAUGHTER",
            maritalStatus: "MARRIED",
            marriageDate: "2021-02-10",
            isDivorced: false,
            religion: "HINDU",
            casteCategory: "OBC",
            includeInSurvey: false,
        }),
        buildPersonRecord({
            id: "27777777-7777-7777-7777-777777777777",
            householdId: household.id,
            fullName: "Kavita Patil",
            relationToLandOwner: "DAUGHTER",
            maritalStatus: "DIVORCED",
            isDivorced: true,
            religion: "HINDU",
            casteCategory: "OBC",
            dependentOnLandOwner: true,
        }),
    ];
    return {
        household,
        persons,
        familyGroups: buildFamilyGroups(persons),
        landDetails: buildLandDetails(household.id, 82, 45, "Pucca"),
        valuation: buildValuation({
            householdId: household.id,
            structureValue: 850000,
            landValue: 1250000,
            treeAssetValue: 20000,
            shiftingAllowance: 50000,
            subsistenceAllowance: 30000,
            otherAssistance: 0,
        }),
    };
})();
